ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    SENHA VARCHAR2(200) NOT NULL,
    TIPO_USUARIO VARCHAR2(20) NOT NULL,
    DATA_CADASTRO DATE DEFAULT SYSDATE
);
