ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

-- TABELA USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL
);

-- TABELA PERFIL
CREATE TABLE PERFIL (
    ID_PERFIL NUMBER NOT NULL,
    NOME_PERFIL VARCHAR2(50) NOT NULL
);

-- TABELA USUARIO_PERFIL
CREATE TABLE USUARIO_PERFIL (
    ID_USUARIO NUMBER NOT NULL,
    ID_PERFIL NUMBER NOT NULL
);

-- TABELA CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL
);

-- TABELA VENDEDOR
CREATE TABLE VENDEDOR (
    ID_VENDEDOR NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL
);

-- TABELA ESTADO
CREATE TABLE ESTADO (
    ID_ESTADO NUMBER NOT NULL,
    SIGLA CHAR(2) NOT NULL,
    NOME VARCHAR2(100) NOT NULL
);

-- TABELA ENDERECO
CREATE TABLE ENDERECO (
    ID_ENDERECO NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    RUA VARCHAR2(150) NOT NULL,
    NUMERO VARCHAR2(10) NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    CEP VARCHAR2(10) NOT NULL,
    ID_ESTADO NUMBER NOT NULL
);

-- TABELA CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL
);

-- TABELA SUBCATEGORIA
CREATE TABLE SUBCATEGORIA (
    ID_SUBCATEGORIA NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL
);

-- TABELA PRODUTO
CREATE TABLE PRODUTO (
    ID_PRODUTO NUMBER NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    DESCRICAO CLOB,
    PRECO NUMBER(10,2) NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    ID_SUBCATEGORIA NUMBER NOT NULL,
    ID_VENDEDOR NUMBER NOT NULL
);

-- TABELA ESTOQUE
CREATE TABLE ESTOQUE (
    ID_ESTOQUE NUMBER NOT NULL,
    ID_PRODUTO NUMBER NOT NULL,
    QUANTIDADE NUMBER NOT NULL
);

-- TABELA STATUS_PEDIDO
CREATE TABLE STATUS_PEDIDO (
    ID_STATUS NUMBER NOT NULL,
    DESCRICAO VARCHAR2(50) NOT NULL
);

-- TABELA PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    DATA_PEDIDO TIMESTAMP NOT NULL,
    ID_STATUS NUMBER NOT NULL
);

-- TABELA ITEM_PEDIDO
CREATE TABLE ITEM_PEDIDO (
    ID_ITEM NUMBER NOT NULL,
    ID_PEDIDO NUMBER NOT NULL,
    ID_PRODUTO NUMBER NOT NULL,
    QUANTIDADE NUMBER NOT NULL,
    PRECO_UNITARIO NUMBER(10,2) NOT NULL
);


-- TABELA FORMA_PAGAMENTO
CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO NUMBER NOT NULL,
    DESCRICAO VARCHAR2(50) NOT NULL
);

-- TABELA PAGAMENTO
CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO NUMBER NOT NULL,
    ID_PEDIDO NUMBER NOT NULL,
    ID_FORMA_PAGAMENTO NUMBER NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DATA_PAGAMENTO TIMESTAMP NOT NULL
);

-- TABELA AVALIACAO
CREATE TABLE AVALIACAO (
    ID_AVALIACAO NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    ID_PRODUTO NUMBER NOT NULL,
    NOTA NUMBER NOT NULL,
    COMENTARIO CLOB,
    DATA_AVALIACAO TIMESTAMP NOT NULL
);
