ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO
PRIMARY KEY (ID_USUARIO);

ALTER TABLE USUARIO
ADD CONSTRAINT UK_USUARIO_EMAIL
UNIQUE (EMAIL);

ALTER TABLE USUARIO
ADD CONSTRAINT CK_USUARIO_TIPO
CHECK (TIPO_USUARIO IN ('CLIENTE', 'VENDEDOR'));
