-- PRIMARY KEYS

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO);

ALTER TABLE PERFIL ADD CONSTRAINT PK_PERFIL PRIMARY KEY (ID_PERFIL);

ALTER TABLE USUARIO_PERFIL ADD CONSTRAINT PK_USUARIO_PERFIL
PRIMARY KEY (ID_USUARIO, ID_PERFIL);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE);

ALTER TABLE VENDEDOR ADD CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID_VENDEDOR);

ALTER TABLE ESTADO ADD CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO);

ALTER TABLE ENDERECO ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_ENDERECO);

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA);

ALTER TABLE SUBCATEGORIA ADD CONSTRAINT PK_SUBCATEGORIA PRIMARY KEY (ID_SUBCATEGORIA);

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO);

ALTER TABLE ESTOQUE ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (ID_ESTOQUE);

ALTER TABLE STATUS_PEDIDO ADD CONSTRAINT PK_STATUS_PEDIDO PRIMARY KEY (ID_STATUS);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO);

ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY (ID_ITEM);

ALTER TABLE FORMA_PAGAMENTO ADD CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY (ID_FORMA_PAGAMENTO);

ALTER TABLE PAGAMENTO ADD CONSTRAINT PK_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO);

ALTER TABLE AVALIACAO ADD CONSTRAINT PK_AVALIACAO PRIMARY KEY (ID_AVALIACAO);


-- UNIQUE

ALTER TABLE USUARIO ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL);

ALTER TABLE ESTADO ADD CONSTRAINT UK_ESTADO_SIGLA UNIQUE (SIGLA);

-- FOREIGN KEYS

ALTER TABLE USUARIO_PERFIL
ADD CONSTRAINT FK_UP_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE USUARIO_PERFIL
ADD CONSTRAINT FK_UP_PERFIL
FOREIGN KEY (ID_PERFIL)
REFERENCES PERFIL(ID_PERFIL);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE VENDEDOR
ADD CONSTRAINT FK_VENDEDOR_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ESTADO
FOREIGN KEY (ID_ESTADO)
REFERENCES ESTADO(ID_ESTADO);

ALTER TABLE SUBCATEGORIA
ADD CONSTRAINT FK_SUBCAT_CATEGORIA
FOREIGN KEY (ID_CATEGORIA)
REFERENCES CATEGORIA(ID_CATEGORIA);

ALTER TABLE PRODUTO
ADD CONSTRAINT FK_PRODUTO_SUBCAT
FOREIGN KEY (ID_SUBCATEGORIA)
REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA);

ALTER TABLE PRODUTO
ADD CONSTRAINT FK_PRODUTO_VENDEDOR
FOREIGN KEY (ID_VENDEDOR)
REFERENCES VENDEDOR(ID_VENDEDOR);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRODUTO
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTO(ID_PRODUTO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_STATUS
FOREIGN KEY (ID_STATUS)
REFERENCES STATUS_PEDIDO(ID_STATUS);

ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT FK_ITEM_PEDIDO
FOREIGN KEY (ID_PEDIDO)
REFERENCES PEDIDO(ID_PEDIDO);

ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT FK_ITEM_PRODUTO
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTO(ID_PRODUTO);

ALTER TABLE PAGAMENTO
ADD CONSTRAINT FK_PAGAMENTO_PEDIDO
FOREIGN KEY (ID_PEDIDO)
REFERENCES PEDIDO(ID_PEDIDO);

ALTER TABLE PAGAMENTO
ADD CONSTRAINT FK_PAGAMENTO_FORMA
FOREIGN KEY (ID_FORMA_PAGAMENTO)
REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO);

ALTER TABLE AVALIACAO
ADD CONSTRAINT FK_AVALIACAO_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE AVALIACAO
ADD CONSTRAINT FK_AVALIACAO_PRODUTO
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTO(ID_PRODUTO);

-- CHECKS

ALTER TABLE AVALIACAO
ADD CONSTRAINT CK_AVALIACAO_NOTA
CHECK (NOTA BETWEEN 1 AND 5);

ALTER TABLE ESTOQUE
ADD CONSTRAINT CK_ESTOQUE_QTD
CHECK (QUANTIDADE >= 0);

ALTER TABLE ITEM_PEDIDO
ADD CONSTRAINT CK_ITEM_QTD
CHECK (QUANTIDADE > 0);

ALTER TABLE PRODUTO
ADD CONSTRAINT CK_PRODUTO_PRECO
CHECK (PRECO >= 0);
