
-- SEQUENCE USUARIO
CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE PERFIL
CREATE SEQUENCE SEQ_PERFIL
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE CLIENTE
CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE VENDEDOR
CREATE SEQUENCE SEQ_VENDEDOR
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE ESTADO
CREATE SEQUENCE SEQ_ESTADO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE ENDERECO
CREATE SEQUENCE SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE CATEGORIA
CREATE SEQUENCE SEQ_CATEGORIA
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE SUBCATEGORIA
CREATE SEQUENCE SEQ_SUBCATEGORIA
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE PRODUTO
CREATE SEQUENCE SEQ_PRODUTO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE ESTOQUE
CREATE SEQUENCE SEQ_ESTOQUE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE STATUS_PEDIDO
CREATE SEQUENCE SEQ_STATUS_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE PEDIDO
CREATE SEQUENCE SEQ_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE ITEM_PEDIDO
CREATE SEQUENCE SEQ_ITEM_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE FORMA_PAGAMENTO
CREATE SEQUENCE SEQ_FORMA_PAGAMENTO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE PAGAMENTO
CREATE SEQUENCE SEQ_PAGAMENTO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- SEQUENCE AVALIACAO
CREATE SEQUENCE SEQ_AVALIACAO
START WITH 1
INCREMENT BY 1
NOCACHE;
