-- TABELA USUARIO_LOG
CREATE TABLE USUARIO_LOG (
    ID_LOG NUMBER NOT NULL,
    ID_USUARIO NUMBER,
    OPERACAO VARCHAR2(10),
    DATA_OPERACAO TIMESTAMP,
    USUARIO_BANCO VARCHAR2(100),

    NOME_ANTIGO VARCHAR2(100),
    NOME_NOVO VARCHAR2(100),

    EMAIL_ANTIGO VARCHAR2(150),
    EMAIL_NOVO VARCHAR2(150)
);

-- TABELA CLIENTE_LOG
CREATE TABLE CLIENTE_LOG (
    ID_LOG NUMBER NOT NULL,
    ID_CLIENTE NUMBER,
    OPERACAO VARCHAR2(10),
    DATA_OPERACAO TIMESTAMP,
    USUARIO_BANCO VARCHAR2(100),

    ID_USUARIO_ANTIGO NUMBER,
    ID_USUARIO_NOVO NUMBER
);

-- TABELA PRODUTO_LOG
CREATE TABLE PRODUTO_LOG (
    ID_LOG NUMBER NOT NULL,
    ID_PRODUTO NUMBER,
    OPERACAO VARCHAR2(10),
    DATA_OPERACAO TIMESTAMP,
    USUARIO_BANCO VARCHAR2(100),

    NOME_ANTIGO VARCHAR2(150),
    NOME_NOVO VARCHAR2(150),

    PRECO_ANTIGO NUMBER(10,2),
    PRECO_NOVO NUMBER(10,2)
);

-- TABELA PEDIDO_LOG
CREATE TABLE PEDIDO_LOG (
    ID_LOG NUMBER NOT NULL,
    ID_PEDIDO NUMBER,
    OPERACAO VARCHAR2(10),
    DATA_OPERACAO TIMESTAMP,
    USUARIO_BANCO VARCHAR2(100),

    STATUS_ANTIGO NUMBER,
    STATUS_NOVO NUMBER
);

-- TABELA PAGAMENTO_LOG
CREATE TABLE PAGAMENTO_LOG (
    ID_LOG NUMBER NOT NULL,
    ID_PAGAMENTO NUMBER,
    OPERACAO VARCHAR2(10),
    DATA_OPERACAO TIMESTAMP,
    USUARIO_BANCO VARCHAR2(100),

    VALOR_ANTIGO NUMBER(10,2),
    VALOR_NOVO NUMBER(10,2)
);
