-- INSERTS

INSERT INTO PERFIL VALUES (1, 'CLIENTE');
INSERT INTO PERFIL VALUES (2, 'VENDEDOR');
INSERT INTO PERFIL VALUES (3, 'ADMIN');

INSERT INTO ESTADO VALUES (1, 'SP', 'São Paulo');
INSERT INTO ESTADO VALUES (2, 'RJ', 'Rio de Janeiro');
INSERT INTO ESTADO VALUES (3, 'MG', 'Minas Gerais');

INSERT INTO USUARIO (
    ID_USUARIO,
    NOME,
    EMAIL,
    SENHA,
    DATA_CADASTRO
)
VALUES (
    1,
    'Maria Luiza',
    'malu@email.com',
    '123456',
    SYSTIMESTAMP
);

INSERT INTO USUARIO (
    ID_USUARIO,
    NOME,
    EMAIL,
    SENHA,
    DATA_CADASTRO
)
VALUES (
    2,
    'João Silva',
    'joao@email.com',
    '123456',
    SYSTIMESTAMP
);

INSERT INTO USUARIO_PERFIL VALUES (1, 1);
INSERT INTO USUARIO_PERFIL VALUES (2, 2);

INSERT INTO CLIENTE VALUES (1, 1);

INSERT INTO VENDEDOR VALUES (1, 2);


INSERT INTO ENDERECO (
    ID_ENDERECO,
    ID_USUARIO,
    RUA,
    NUMERO,
    CIDADE,
    CEP,
    ID_ESTADO
)
VALUES (
    1,
    1,
    'Rua das Flores',
    '100',
    'São Paulo',
    '01000-000',
    1
);

INSERT INTO CATEGORIA VALUES (1, 'Eletrônicos');
INSERT INTO CATEGORIA VALUES (2, 'Roupas');

INSERT INTO SUBCATEGORIA VALUES (1, 'Celulares', 1);
INSERT INTO SUBCATEGORIA VALUES (2, 'Notebooks', 1);

INSERT INTO PRODUTO (
    ID_PRODUTO,
    NOME,
    DESCRICAO,
    PRECO,
    DATA_CADASTRO,
    ID_SUBCATEGORIA,
    ID_VENDEDOR
)
VALUES (
    1,
    'iPhone 15',
    'Smartphone Apple',
    7500.00,
    SYSTIMESTAMP,
    1,
    1
);

INSERT INTO ESTOQUE VALUES (1, 1, 50);

INSERT INTO STATUS_PEDIDO VALUES (1, 'PENDENTE');
INSERT INTO STATUS_PEDIDO VALUES (2, 'PAGO');
INSERT INTO STATUS_PEDIDO VALUES (3, 'ENVIADO');
INSERT INTO STATUS_PEDIDO VALUES (4, 'ENTREGUE');

INSERT INTO PEDIDO (
    ID_PEDIDO,
    ID_CLIENTE,
    DATA_PEDIDO,
    ID_STATUS
)
VALUES (
    1,
    1,
    SYSTIMESTAMP,
    1
);

INSERT INTO ITEM_PEDIDO (
    ID_ITEM,
    ID_PEDIDO,
    ID_PRODUTO,
    QUANTIDADE,
    PRECO_UNITARIO
)
VALUES (
    1,
    1,
    1,
    2,
    7500.00
);

INSERT INTO FORMA_PAGAMENTO VALUES (1, 'Cartão de Crédito');
INSERT INTO FORMA_PAGAMENTO VALUES (2, 'PIX');
INSERT INTO FORMA_PAGAMENTO VALUES (3, 'Boleto');

INSERT INTO PAGAMENTO (
    ID_PAGAMENTO,
    ID_PEDIDO,
    ID_FORMA_PAGAMENTO,
    VALOR,
    DATA_PAGAMENTO
)
VALUES (
    1,
    1,
    1,
    15000.00,
    SYSTIMESTAMP
);

INSERT INTO AVALIACAO (
    ID_AVALIACAO,
    ID_CLIENTE,
    ID_PRODUTO,
    NOTA,
    COMENTARIO,
    DATA_AVALIACAO
)
VALUES (
    1,
    1,
    1,
    5,
    'Excelente produto',
    SYSTIMESTAMP
);

COMMIT;
