-- VIEW 1 - PRODUTOS COMPLETOS
CREATE OR REPLACE VIEW VW_PRODUTOS_COMPLETOS AS
SELECT
    P.ID_PRODUTO,
    P.NOME AS PRODUTO,
    P.PRECO,
    S.NOME AS SUBCATEGORIA,
    C.NOME AS CATEGORIA,
    U.NOME AS VENDEDOR
FROM PRODUTO P
INNER JOIN SUBCATEGORIA S
    ON P.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
INNER JOIN CATEGORIA C
    ON S.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN VENDEDOR V
    ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN USUARIO U
    ON V.ID_USUARIO = U.ID_USUARIO;


-- VIEW 2 - CLIENTES
CREATE OR REPLACE VIEW VW_CLIENTES AS
SELECT
    C.ID_CLIENTE,
    U.NOME,
    U.EMAIL,
    U.DATA_CADASTRO
FROM CLIENTE C
INNER JOIN USUARIO U
    ON C.ID_USUARIO = U.ID_USUARIO;


-- VIEW 3 - VENDEDORES
CREATE OR REPLACE VIEW VW_VENDEDORES AS
SELECT
    V.ID_VENDEDOR,
    U.NOME,
    U.EMAIL
FROM VENDEDOR V
INNER JOIN USUARIO U
    ON V.ID_USUARIO = U.ID_USUARIO;


-- VIEW 4 - PEDIDOS COMPLETOS
CREATE OR REPLACE VIEW VW_PEDIDOS_COMPLETOS AS
SELECT
    P.ID_PEDIDO,
    U.NOME AS CLIENTE,
    SP.DESCRICAO AS STATUS_PEDIDO,
    P.DATA_PEDIDO
FROM PEDIDO P
INNER JOIN CLIENTE C
    ON P.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN USUARIO U
    ON C.ID_USUARIO = U.ID_USUARIO
INNER JOIN STATUS_PEDIDO SP
    ON P.ID_STATUS = SP.ID_STATUS;


-- VIEW 5 - ITENS PEDIDO
CREATE OR REPLACE VIEW VW_ITENS_PEDIDO AS
SELECT
    IP.ID_ITEM,
    IP.ID_PEDIDO,
    PR.NOME AS PRODUTO,
    IP.QUANTIDADE,
    IP.PRECO_UNITARIO
FROM ITEM_PEDIDO IP
INNER JOIN PRODUTO PR
    ON IP.ID_PRODUTO = PR.ID_PRODUTO;


-- VIEW 6 - ESTOQUE PRODUTO
CREATE OR REPLACE VIEW VW_ESTOQUE_PRODUTO AS
SELECT
    P.ID_PRODUTO,
    P.NOME,
    E.QUANTIDADE
FROM PRODUTO P
INNER JOIN ESTOQUE E
    ON P.ID_PRODUTO = E.ID_PRODUTO;


-- VIEW 7 - PAGAMENTOS
CREATE OR REPLACE VIEW VW_PAGAMENTOS AS
SELECT
    PG.ID_PAGAMENTO,
    PD.ID_PEDIDO,
    FP.DESCRICAO AS FORMA_PAGAMENTO,
    PG.VALOR,
    PG.DATA_PAGAMENTO
FROM PAGAMENTO PG
INNER JOIN PEDIDO PD
    ON PG.ID_PEDIDO = PD.ID_PEDIDO
INNER JOIN FORMA_PAGAMENTO FP
    ON PG.ID_FORMA_PAGAMENTO = FP.ID_FORMA_PAGAMENTO;


-- VIEW 8 - AVALIACOES
CREATE OR REPLACE VIEW VW_AVALIACOES AS
SELECT
    A.ID_AVALIACAO,
    U.NOME AS CLIENTE,
    P.NOME AS PRODUTO,
    A.NOTA,
    A.COMENTARIO
FROM AVALIACAO A
INNER JOIN CLIENTE C
    ON A.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN USUARIO U
    ON C.ID_USUARIO = U.ID_USUARIO
INNER JOIN PRODUTO P
    ON A.ID_PRODUTO = P.ID_PRODUTO;


-- VIEW 9 - MEDIA AVALIACAO PRODUTO
CREATE OR REPLACE VIEW VW_MEDIA_AVALIACAO AS
SELECT
    P.ID_PRODUTO,
    P.NOME,
    ROUND(AVG(A.NOTA), 2) AS MEDIA_AVALIACAO
FROM PRODUTO P
INNER JOIN AVALIACAO A
    ON P.ID_PRODUTO = A.ID_PRODUTO
GROUP BY
    P.ID_PRODUTO,
    P.NOME;


-- VIEW 10 - TOTAL VENDAS VENDEDOR
CREATE OR REPLACE VIEW VW_TOTAL_VENDAS_VENDEDOR AS
SELECT
    U.NOME AS VENDEDOR,
    SUM(IP.QUANTIDADE * IP.PRECO_UNITARIO) AS TOTAL_VENDIDO
FROM ITEM_PEDIDO IP
INNER JOIN PRODUTO P
    ON IP.ID_PRODUTO = P.ID_PRODUTO
INNER JOIN VENDEDOR V
    ON P.ID_VENDEDOR = V.ID_VENDEDOR
INNER JOIN USUARIO U
    ON V.ID_USUARIO = U.ID_USUARIO
GROUP BY
    U.NOME;
